name: Tests

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        django-version: [4.0, 3.2]

    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django-cursor-pagination

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Django
        run: pip install django==${{ matrix.django-version }}
      - run: pip install psycopg2
      - run: pip install -e .
      - run: python runtests.py
